### ISSUE TITLE
我修改整合了一下大佬们写的服务启动脚本，但现在还没有设备可以用来测试，大佬们帮我看看整体逻辑上有没有问题

### ISSUE THREAD

**Issue by Droid-MAX** [balthild/agentx1-lede#2]
这是我的仓库地址
https://github.com/Droid-MAX/agentx1
开机服务自启的话感觉好像会有问题，因为没有给enable，是不是应该在Makefile里给加上去？

**Comment by balthild** [comment]
看起来没啥问题。开机自启我没有默认启用，要用户手动 /etc/init.d/agentx1 enable

**Comment by Droid-MAX** [comment]
明白
